[package]
edition.workspace      = true
license-file.workspace = true
name                   = "orion-proxy"
rust-version.workspace = true
version.workspace      = true


[[bin]]
name = "orion"
path = "src/main.rs"

[dependencies]
abort-on-drop.workspace        = true
dhat = { workspace = true, optional = true }
futures.workspace              = true
num_cpus.workspace             = true
orion-configuration.workspace  = true
orion-error.workspace          = true
orion-format.workspace         = true
orion-lib.workspace            = true
orion-stats.workspace          = true
orion-metrics = { workspace = true, optional = true }
orion-tracing.workspace        = true
orion-xds.workspace            = true
parking_lot.workspace          = true
pingora-timeout.workspace      = true
tokio.workspace                = true
tower.workspace                = true
tracing.workspace              = true
ahash.workspace                = true
const_format.workspace         = true
maud.workspace                 = true

axum.workspace = true
smol_str.workspace = true
http.workspace = true
opentelemetry.workspace = true
regex.workspace = true
serde = { workspace = true, features = ["rc"] }
serde_json.workspace = true
thiserror.workspace = true
tracing-appender.workspace = true
tracing-subscriber = { workspace = true, features = [
  "alloc",
  "env-filter",
  "fmt",
  "registry",
  "std",
] }
smallvec.workspace = true

[features]
config-dump = []
dhat-heap   = ["dep:dhat"]
jemalloc    = ["dep:tikv-jemallocator", "orion-metrics/jemalloc", "orion-stats/jemalloc"]
metrics     = ["dep:orion-metrics", "orion-lib/metrics"]
instrumentation = ["orion-lib/instrumentation"]
tracing     = ["orion-lib/tracing"]
access-log  = ["orion-lib/access-log"]
prometheus  = ["metrics"]


[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { workspace = true, optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
caps.workspace = true
affinity.workspace = true

[dev-dependencies]
axum-test.workspace = true
orion-data-plane-api.workspace = true

[lints]
workspace = true
