[package]
name = "header_mutations_filter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# Keep this example crate out of the parent `arion_wasm_sdk` workspace so it
# can be compiled standalone to `wasm32-unknown-unknown`.

[dependencies]
arion_wasm_sdk = { path = "../../" }
tracing = "0.1"
http = "1.0"
bytes = "1.12.1"
smol_str = "0.3.6"
