[package]
edition.workspace      = true
license-file.workspace = true
name                   = "arion-interner"
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
smol_str.workspace = true
http.workspace = true
lasso = { workspace = true, features = [
  "ahash",
  "ahasher",
  "dashmap",
  "multi-threaded",
] }
serde.workspace = true
