syntax = "proto3";

package orion.extensions.filters.http.user_rate_limit.v3;

import "envoy/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto";
import "envoy/type/v3/http_status.proto";
import "validate/validate.proto";
import "google/protobuf/duration.proto";

message SimpleRateLimit {
    uint32 max_tokens = 1;
    uint32 rate = 2;
}

message UserRateLimit {
    optional string user_id = 1;
    oneof limit {
        envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit local_rate_limit = 2;
        SimpleRateLimit simple_rate_limit = 3;
    }
}

// [#protodoc-title: UserRateLimiter Filter]
message UserRateLimiter {
    string user_id_header_name = 1;
    string stat_prefix = 2;
    envoy.type.v3.HttpStatus status = 3;
    repeated UserRateLimit user_rate_limits = 4;
}
