[package]
edition.workspace      = true
license-file.workspace = true
name                   = "orion-stats"
rust-version.workspace = true
version.workspace      = true

[features]
jemalloc = ["dep:tikv-jemalloc-ctl"]

[dependencies]
atomicoption.workspace = true
memory-stats.workspace = true
serde.workspace = true
tikv-jemalloc-ctl = { workspace = true, optional = true, features = ["stats"] }
