[package]
edition.workspace      = true
license-file.workspace = true
name                   = "orion-configuration"
rust-version.workspace = true
version.workspace      = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64.workspace = true
base64-serde.workspace = true
bounded-integer = { workspace = true, features = ["serde1"] }
bytes.workspace = true
smol_str.workspace = true
exponential-backoff.workspace = true
http.workspace = true
num_cpus.workspace = true
orion-error.workspace = true
orion-format.workspace = true
orion-interner.workspace = true
orion-auth.workspace = true
regex.workspace = true
tracing-rolling-file.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
ahash.workspace = true
clap = { workspace = true, features = ["derive"] }
http-serde-ext.workspace = true
humantime-serde.workspace = true
ipnet = { workspace = true, features = ["serde"] }
itertools.workspace = true
opentelemetry-otlp = { workspace = true, features = [
  "serde",
  "serde_json",
  "serialize",
] }
orion-data-plane-api = { workspace = true, optional = true }
serde = { workspace = true, features = ["rc"] }
smallvec = { workspace = true, features = ["serde"] }
serde_path_to_error.workspace = true
serde_regex.workspace = true
tracing-appender = { workspace = true, features = ["parking_lot"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "std"] }
jsonschema.workspace = true


[dev-dependencies]
tracing-test.workspace = true
tempfile.workspace = true

[features]
default           = ["envoy-conversions"]
envoy-conversions = ["dep:orion-data-plane-api"]


[lints]
workspace = true
